### ISSUE TITLE
Linear Algebra Review Questions

### ISSUE THREAD

**Issue by xuemeic** [Numerical-Analysis/course#4]
@Numerical-Analysis/everyone 

I have posted a few very basic [linear algebra review questions](https://github.com/Numerical-Analysis/course/blob/master/other/LAreviewQ.pdf). Please work on them as a way to test yourself. There is no need to turn them in, but we will have a quiz based on these questions on Thursday 9/14.

Feel free to ask linear algebra questions under this issue. Answer (without full solution) will be provided later. You can also ask me here or email me for answers.

**Comment by xuemeic** [comment]
@jeancarlosp 

Second page has answers.

[LAreviewQ.pdf](https://github.com/Numerical-Analysis/course/files/1296916/LAreviewQ.pdf)

**Comment by Aebravo** [comment]
Hi, I am having trouble accessing the solutions. The pdf won’t open.

**Comment by xuemeic** [comment]
@Aebravo The pdf just gets downloaded if I click on it.

**Comment by xuemeic** [comment]
Sorry that I just found a typo on problem 10(a), it should be "Find all linear combinations of a_1, a_2, a_3 that makes up b_1 if answer is yes."

**Comment by ghost** [comment]
FYI, 
So for #9.A, the Matrix has Infinite Solutions, instead of One Solution.
